config/routes.rb
Rails.application.routes.draw do

  resources :users do
    member do
      post 'toggle_activation'
      post 'toggle_promotion'
      post 'toggle_follow'
      get 'profile_view' 
      post 'restore'
    end
    collection do

    end
  end

  resources :questions do 
  resources :answers 
end
  post 'answers/:id/like' => 'answers#toggle_like', :as => :answer_toggle_like
  root 'page#home'
  
  get 'login' => 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
 

end

app/models/question.rb
class Question < ActiveRecord::Base

	belongs_to :user, inverse_of: :questions
	has_many :answers, foreign_key: :ques_id, dependent: :destroy
	validates :question, :presence => true

	def author?(current_user)
		user_id == current_user.id
	end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	before_action :load_question, only: [:index, :edit, :update, :destroy, :show]

	def index
		if Question.all.present?
			@question = Question.all
			# followers_user_id = current_user.followings.order("first_name, last_name").map(&:id)
			# @question = Question.joins(:user).includes(:user)
			# all_user_id = @question.order("users.first_name, users.last_name").map(&:user_id)
			# order_users = followers_user_id | all_user_id
			# @question = @question.order("FIELD(user_id, #{order_users.join(',')})")
		else
			flash[:danger] = "No Questions to load add a new one"
			@question = Question.new
			render :new
		end
	end

	def new
		@question = Question.new
	end

	def create
		@question = Question.new(question_params)
		@question.user = current_user
		if @question.save
			redirect_to question_path(@question.id), success: "Question created successfully"	
		else
			flash[:danger] = "check fields"
            render :new
        end
	end

	def edit
		redirect_to questions_path, danger: "Question not found" unless @question.present? && @question.author?(current_user)
	end

	def update	
		if @question.update(question_params)
            redirect_to questions_path, success: "Updated successfully" 
        else
        	flash[:danger] = "check fields"
            render :new
        end
	end

	def show
		# @answer = Answer.order("vote_count DESC").where("ques_id = ?", params[:id])
		if @question.present?
			@answer = @question.answers.joins(:user).includes(:voters).order("vote_count DESC")
		else
			redirect_to questions_path, danger: "Invalid operation"
		end
	end

	def destroy
		if @question.author?(current_user)
			@question.destroy
			redirect_to questions_path, success: "Deleted successfully"
        else
        	redirect_to questions_path, danger: "Question not found"
        end
	end

	private
	
	def question_params
		params.require(:question).permit(:question)
	end

	def load_question
		@question= Question.find_by(id: params[:id])
	end

end

app/views/questions/_form.html.erb
<% if @question.question.present? %>
<center>
	<b>Question : </b><%= @question.question %><br>
	<b>Question created by :</b> <%= @question.user.full_name %></center>
<% end %>

<div class="row">
	<div class="col-sm-12">
		<%= form_for(@question)  do |f| %>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :question %>
				</div>
				<div class="col-sm-8">
					<%= f.text_field :question, class: "form-control", placeholder: "question", autofocus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-8 col-sm-offset-2">
					<%= f.submit %>
				</div>
			</div>
		<%end%>
	</div>
</div>

app/views/questions/edit.html.erb
<%= render 'form'%>

app/views/questions/index.html.erb
<% if @question.present? %>
  <h2 style="text-align: center;"> QUESTIONS </h2>
  <table class="table table-borderless table-hover">
    <thead class="thead-dark">
      <tr>
        <th>S.no</th>
        <th>Question</th>
        <th>Created By</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <% s_no=1%>
      <% @question.each do |question| %>
        <tr>
          <td><%= s_no %></td><%s_no+=1%>
          <td><b><%= link_to "#{question.question}" , question_path(question.id), class: "no-decoration" %></b></td>
          <td><%= link_to "#{question.user.full_name}", user_path(question.user_id), class: "no-decoration" %></td>
          <% if question.author?(current_user) %>
            <td><%= link_to 'Update', edit_question_path(question.id), class:"btn btn-warning"%></td>
            <td><%= link_to 'Delete', question_path(question.id), class:"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% else %>
            <td></td>
            <td></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <h3><%= link_to 'New', new_question_path, class:"btn btn-warning" %></h3>
<% else %>
  <%= redirect_to root_path, danger: "No questions to load" %>
<% end %>

app/views/questions/new.html.erb
<%= render 'form'%>

app/views/questions/show.html.erb
 
<h2 style="text-align: center;"> ANSWERS </h2>
<b>Question : </b><%= @question.question %><br>
<b>Question created by :</b> <%= @question.user.full_name %><br><br>

<% if @answer.present? %>
<table class="table table-borderless table-hover"> 
  <thead class="thead-dark">
    <tr>
      <th>S.no</th>
      <th>Answers</th>
      <th>Posted By</th>
      <th>Update</th>
      <th>Delete</th>
      <th>Like / Unlike</th>
      <th>Vote count</th>
    </tr>
  </thead>
  <tbody>
    <% s_no=1%>
    <% @answer.each do |answer| %>
      <tr>

        <td><%= s_no %></td><%s_no+=1%>
        <td><%= answer.answer %></td>
        <td><%= link_to "#{answer.user.full_name}", user_path(answer.user_id), class: "no-decoration" %></td>
        <% if answer.author?(current_user)   %>
            <td><%= link_to 'Update', edit_question_answer_path(@question.id,answer.id), class:"btn btn-warning"%></td>
            <td><%= link_to 'Delete', question_answer_path(@question.id,answer.id), class:"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
            <td></td>
            <td></td>
        <% end %>
        <% if answer.voted?(current_user) %>
          <td><%= link_to 'Unlike', answer_toggle_like_path(answer.id), class:"btn btn-light", method: :post %>
          </td>
        <% else %>
        
          <td><%= link_to 'Like', answer_toggle_like_path(answer.id), class:"btn btn-dark", method: :post %></td>
        <% end %>
        
        <td><%= answer.vote_count %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<% end %>
<%= link_to 'post answer', new_question_answer_path(@question.id), class:"btn btn-warning"%><br>