config/routes.rb
Rails.application.routes.draw do

  resources :users do
    member do
      post 'toggle_activation'
      post 'toggle_promotion'
      post 'toggle_follow'
      get 'profile_view' 
      post 'restore'
    end
    collection do

    end
  end

  resources :questions do 
  resources :answers 
end
  post 'answers/:id/like' => 'answers#toggle_like', :as => :answer_toggle_like
  root 'page#home'
  
  get 'login' => 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
 

end

app/models/user.rb
class User < ActiveRecord::Base

	before_destroy :check_admins_present, if: -> { self.admin?}	
	has_many :following_relations, class_name: "Relationship" , foreign_key: "following_id", dependent: :destroy
	has_many :follower_relations, class_name: "Relationship" ,foreign_key: "follower_id", dependent: :destroy
	has_many :followings, through: :follower_relations
	has_many :followers, through: :following_relations
	has_many :questions, dependent: :destroy
	has_many :answers, dependent: :destroy
	has_many :answervotes

	# before_update :check_admins_present, if: -> { self.admin? && self.deleted_changed? }
	scope :admin_count, -> { where(admin: true).count(:admin) }
	# default_scope { where(:deleted => false) }
	validates :email, :presence => true, :uniqueness => true, format: { with: URI::MailTo::EMAIL_REGEXP }
	validates :first_name, :presence => true
	validates :last_name, :presence => true
	validates :mobile_number, :presence => true
	validates :age, :presence => true
	validates :batch, :presence => true
	validates :degree, :presence => true
	validates :college_name, :presence => true
	validates :register_number, :presence => true, :uniqueness => true
	has_secure_password 

	def full_name
		"#{first_name} #{last_name}"
	end

	def title
		admin? ? "Admin" : "User"
	end

	def status
		active? ? "Active" : "Deactive"
	end

	def check_admins_present
		self.errors.add(:base, "Atleast 1 admin must be present") and return false if User.admin_count == 1
		# if self.changes["deleted"] == [false, true] && User.admin_count == 1
	end

	

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

skip_before_action :verify_logged_in, only: [:new, :create]
before_action :load_user, only: [:update, :toggle_activation, :destroy, :toggle_promotion, :show, :profile_view]

	def new
		@user = User.new 
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to root_path, success: "Account created successfully, wait till it gets activated"
		else
			flash[:danger] = "check fields"
			render :new  

		end
	end

	def edit
		if current_user.id == params[:id].to_i
			load_user
		else
			redirect_to root_path, danger: "User not found"
		end 		
	end

	def update
		if @user.update(user_params)
            redirect_to root_path, success: "Updated successfully" 
        else
            render :edit
        end
	end

	def index 
		if current_user.admin?
			@user = User.unscoped.all.order("admin DESC" ,"register_number")
		else
			@user = User.all.where(active: true)
		end
	end

	def destroy 
		# if @user.update_attribute(:deleted, true)
		# 	UserDeleteWorker.perform_at(15.minutes.from_now, @user.id)
		# 	redirect_to users_path, success: "Deleted successfully"
		# else
		# 	redirect_to users_path, danger: @user.errors.messages.values.join('\n')
		# end
		if @user.destroy
			redirect_to users_path, success: "Deleted successfully"
		else
			redirect_to users_path, danger: @user.errors.messages.values.join('\n')
		end
	end

	# def restore
	# 	@user = User.unscoped.find_by(id: params[:id])
	# 	@user.update_attribute(:deleted, false)
	# 	redirect_to users_path, success: "Restored successfully"
	# end

	def toggle_activation
		@user.update_attribute(:active, !@user.active)
		redirect_to user_path
	end

	def toggle_promotion
		if @user.admin?
			@user.update_attribute(:admin, false)
		else
			@user.update({admin: true, active: true})
		end
		redirect_to user_path
	end

	def toggle_follow
		if @follow_check = Relationship.find_by(following_id: params[:id], follower_id: current_user.id)
			@follow_check.destroy
		else
			Relationship.create(following_id: params[:id], follower_id: current_user.id)
		end
		redirect_to user_path(params[:id])
	end

	def show
		if @user.present?
			@following =  @user.followings
			@follower =  @user.followers
		else
			redirect_to root_path, danger: "Invalid Operation"
		end
	end

	def profile_view
		if  current_user.id == params[:id].to_i
			@following =  @user.followings
			@follower =  @user.followers
		else
			redirect_to root_path, danger: "Invalid Operation"
		end
	end


	private
	
	def user_params
		params.require(:user).permit(:first_name, :last_name, :mobile_number, :age, :batch, :degree, :college_name, :register_number, :company_name, :designation, :location, :email, :password)
	end

	def load_user
		@user = User.find_by(id: params[:id])
	end
end

app/views/users/_follower.html.erb
<br>
<h3>Followers : <%= @follower.count %></h3>
<% if @follower.present? %>
<table class="table table-borderless"> 
  <thead class="thead-dark">
    <tr>   
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <% @follower.each do |follower| %>
      <tr>  
        <td><%= link_to "#{follower.full_name}", user_path(follower.id), class: "no-decoration" %></td> 
       </tr>
   	<% end %>
  </tbody>
</table>
<% end %>
<br>

app/views/users/_following.html.erb
<br>
<h3>Followings : <%= @following.count %></h3>
<% if @following.present? %>
<table  class="table table-borderless"> 
  <thead class="thead-dark">
    <tr>   
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <% @following.each do |following| %>
      <tr>  
        <td><%= link_to "#{following.full_name}", user_path(following.id), class: "no-decoration" %></td>
       </tr>
   	<% end %>
  </tbody>
</table>
<% end %>
<br>

app/views/users/_form.html.erb
<div class="row">
	<div class="col-sm-12">
		<%= form_for(@user)  do |f| %>

			<% if @user.errors.any? %>
			<div class = "error-red">
				<span class="close-error">x</span>
				<h3>Errors</h3>
				<ul>
				  <% @user.errors.full_messages.each do |msg| %>
				    <li><%= msg %></li>
				  <% end %>
				</ul>
				</div>
			<% end %>
			

			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :first_name%>
				</div>
				<div class="col-sm-8">
					<%= f.text_field :first_name, class: "form-control", placeholder: "Enter Firstname", autofocus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :last_name %>
				</div>
				<div class="col-sm-8">
					<%= f.text_field :last_name, class: "form-control", placeholder: "Enter Lastname", autofocus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :mobile_number %>
				</div>
				<div class="col-sm-8">
					<%= f.number_field :mobile_number, class: "form-control", placeholder: "Enter mobilenumber", autofocus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :age %>
				</div>
				<div class="col-sm-8">
					<%= f.number_field :age, class: "form-control", placeholder: "Enter age", autofocus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :batch %>
				</div>
				<div class="col-sm-8">
					<%= f.text_field :batch, class: "form-control", placeholder: "Enter batch (eg. 2016-2020)", autofocus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :degree %>
				</div>
				<div class="col-sm-8 ">
					<%= f.select(:degree, ['B.Tech - IT'], {}, { :class => 'form-control' }) %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :collegename %>
				</div>
				<div class="col-sm-8">
					<%= f.select(:college_name, ["St.Joseph's Institute of Technology"], {}, { :class => 'form-control' }) %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :register_number %>
				</div>
				<div class="col-sm-8">
					<%= f.number_field :register_number, :readonly => f.object.persisted?, class: "form-control", placeholder: "Enter register number", autofocus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :company_name %>
				</div>
				<div class="col-sm-8">
					<%= f.text_field :company_name, class: "form-control", placeholder: "Enter company name", autofocus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :designation %>
				</div>
				<div class="col-sm-8">
					<%= f.text_field :designation, class: "form-control", placeholder: "Enter designation", autofocus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :location %>
				</div>
				<div class="col-sm-8">
					<%= f.text_field :location, class: "form-control", placeholder: "Enter location", autofocus: true %>
				</div>
			</div>
			
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :email%>
				</div>
					<div class="col-sm-8">
						<%= f.email_field :email, :readonly => f.object.persisted?,class:"form-control",placeholder: "Enter email"  %>
					</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :password%>
				</div>
				<div class="col-sm-8">
					<%= f.password_field :password,class:"form-control",placeholder: "Enter password" %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-8 col-sm-offset-2">
					<%= f.submit %>
				</div>
			</div>

		<%end%>
	</div>
</div>

<script>
var phone = $("input#user_mobile_number").val();
    if (phone !== "" && !$.isNumeric(phone)) {
  //Check if phone is numeric
  $("label#phone_error").show(); //Show error
  $("input#phone").focus(); //Focus on field
  //return false;
}
var reg_num = $("input#user_register_number").val();
    if (reg_num !== "" && !$.isNumeric(reg_num)) {
  //Check if phone is numeric
  $("label#phone_error").show(); //Show error
  $("input#phone").focus(); //Focus on field
  //return false;
}
var reg_num = $("input#user_register_number").val();
    if (reg_num !== "" && !$.isNumeric(reg_num)) {
  //Check if phone is numeric
  $("label#phone_error").show(); //Show error
  $("input#phone").focus(); //Focus on field
  //return false;
}
var age = $("input#user_age").val();
    if (age !== "" && !$.isNumeric(age)) {
  //Check if phone is numeric
  $("label#phone_error").show(); //Show error
  $("input#phone").focus(); //Focus on field
  //return false;
}
$(".close-error").click(function(){
  $(".error-red").animate({opacity:0}, 500);
});

</script>

app/views/users/index.html.erb
<div >
<% if @user.present? %>
 <table class="table table-borderless table-hover">
  <thead class="thead-dark">
    <tr>
      
      <th>Name</th>
      <th>Batch</th>
      <th>Degree</th>
      <th>Register number</th>
      <th>Email</th>
      

      <% if current_user.admin? %>
      <th>Role</th>
      <th>Delete</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    
    <% @user.each do |user| %> 
      <tr>
        
        <td><b><%= link_to "#{user.full_name}" , user_path(user.id), class: "no-decoration" %></b></td>
        <td><%= user.batch %></td>
        <td><%= user.degree %></td>
        <td><%= user.register_number %></td>
        <td><%= user.email %></td>
       
        <% if current_user.admin? %>
           <% if user.deleted? %>
             <td><div class="badge badge-danger">Deleted</div></td>
           <% else %>
              <td><div class="badge badge-<%= user.admin? ? 'primary' : 'warning'  %>"><%= user.title %></div> <div class="badge badge-<%= user.active? ? 'success' : 'danger'  %>"><%= user.status %></div></td>
          <% end %>
          <% if user.admin? %>
              <% if current_user == user %>
                <td></td>
              <% else %>
                <% if user.deleted? %>
                    <td><%= link_to 'Restore', restore_user_path(user.id), class:"btn btn-warning", method: :post, data: { confirm: 'Are you sure?' }%></td>
                <% else %>
                    <td><%= link_to 'Delete', user_path(user.id), class:"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' }%></td>
                <% end %>
              <% end %>
          <% else %>
            <% if user.deleted? %>
                    <td><%= link_to 'Restore', restore_user_path(user.id), class:"btn btn-warning", method: :post, data: { confirm: 'Are you sure?' }%></td>
                <% else %>
                    <td><%= link_to 'Delete', user_path(user.id), class:"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' }%></td>
                <% end %>
          <% end %>
        <% end %> 
      </tr>
     <% end %>
  </tbody>
</table>
<% end %>




</div>

app/views/users/new.html.erb
<h1>Sign up </h1>


<%= render 'form'%>

app/views/users/profile_view.html.erb
<div class="button-inline">
<div class="float-left">
<table class="table table-borderless">
<tr><td><b>First name</b> </td><td> <%= @user.first_name %></td></tr>
<tr><td><b>Last name</b> </td><td> <%= @user.last_name %></td></tr>
<tr><td><b>Mobile number</b> </td><td> <%= @user.mobile_number %></td></tr>
<tr><td><b>Age</b> </td><td> <%= @user.age %></td></tr>
<tr><td><b>Batch</b> </td><td> <%= @user.batch %></td></tr>
<tr><td><b>Degree</b> </td><td> <%= @user.degree %></td></tr>
<tr><td><b>College name</b> </td><td>  <%= @user.college_name %></td></tr>
<tr><td><b>Register number</b> </td><td> <%= @user.register_number %></td></tr>
<tr><td><b>Company name</b> </td><td> <%= @user.company_name %></td></tr>
<tr><td><b>Designation</b> </td><td> <%= @user.designation %></td></tr>
<tr><td><b>Location</b> </td><td> <%= @user.location %></td></tr>
<tr><td><b>Email</b> </td><td> <%= @user.email %></td></tr>
</table>
<h3><%= link_to 'Edit', edit_user_path(current_user.id), class:"btn btn-warning" %></h3>

</div>
</div>
<div class="float-right" style="margin-right: 40%">
<%= render partial: "following" %>
<%= render partial: "follower" %>
</div>

app/views/users/show.html.erb
<div class="float-left">
<table class="table table-borderless">
<tr><td><b>First name</b> </td><td> <%= @user.first_name %></td></tr>
<tr><td><b>Last name</b> </td><td> <%= @user.last_name %></td></tr>
<tr><td><b>Mobile number</b> </td><td> <%= @user.mobile_number %></td></tr>
<tr><td><b>Age</b> </td><td> <%= @user.age %></td></tr>
<tr><td><b>Batch</b> </td><td> <%= @user.batch %></td></tr>
<tr><td><b>Degree</b> </td><td> <%= @user.degree %></td></tr>
<tr><td><b>College name</b> </td><td>  <%= @user.college_name %></td></tr>
<tr><td><b>Register number</b> </td><td> <%= @user.register_number %></td></tr>
<tr><td><b>Company name</b> </td><td> <%= @user.company_name %></td></tr>
<tr><td><b>Designation</b> </td><td> <%= @user.designation %></td></tr>
<tr><td><b>Location</b> </td><td> <%= @user.location %></td></tr>
<tr><td><b>Email</b> </td><td> <%= @user.email %></td></tr>
</table>

<% if current_user.admin? %>

	

	<div class="button-inline">
	<% if @user.admin? %>
			<h3>
	        <%= link_to 'Revoke', toggle_promotion_user_path(id: @user.id),class:"btn btn-danger", method: :post unless current_user == @user %></h3>
	<% else %>
			<h3><% user_status = @user.active? ? ['Deactivate', 'danger'] : ['Activate', "success"] %>
	        	<%= link_to "#{user_status[0]}", toggle_activation_user_path(id: @user.id),  method: :post, class: "btn btn-#{user_status[1]}" %></h3>
	   
	        <h3><%= link_to 'Promote', toggle_promotion_user_path(id: @user.id),class:"btn btn-success", method: :post if current_user.admin? %></h3>
	<% end %>
	 <h3><%= link_to 'Delete', user_path(@user.id),class:"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } unless current_user == @user %></h3>

<% end %>
<% unless current_user == @user %>
	<% if current_user.followings.find_by(id: @user) %>
	    <h3><%= link_to 'Unfollow', toggle_follow_user_path(@user.id),class:"btn btn-danger", method: :post %></h3>
	<% else %>
		<h3><%= link_to 'Follow', toggle_follow_user_path(@user.id),class:"btn btn-success", method: :post %></h3>
	<% end %>
<% end %>



</div>
</div>



<div class="float-right" style="margin-right: 40%">
<%= render partial: "following" %>
<%= render partial: "follower" %>
</div>