config/routes.rb
Rails.application.routes.draw do

  resources :users do
    member do
      post 'toggle_activation'
      post 'toggle_promotion'
      post 'toggle_follow'
      get 'profile_view' 
      post 'restore'
    end
    collection do

    end
  end

  resources :questions do 
  resources :answers 
end
  post 'answers/:id/like' => 'answers#toggle_like', :as => :answer_toggle_like
  root 'page#home'
  
  get 'login' => 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
 

end

app/views/layouts/_flash.html.erb
<%flash.each do |key,value|%>
	<div class='alert alert-<%= key %>'>
		<%=value%>
	</div>
<%end%>

app/views/layouts/_headernav.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
	<a class="navbar-brand" href="http://www.stjosephstechnology.ac.in/web/index.html" target="_blank">
		<%= image_tag("sjit-logo.png", width: '61', height:'66', class:'d-inline-block align-top') %>
    <%= link_to 'BROGRAMMERS', root_path , class: "nav-color"%>
  </a>
<ul class="navbar-nav">
<% if current_user && current_user.active %>
	<li class="nav-item"><div class="nav-link"><%= link_to 'Users', users_path, class: "nav-color"%></div></li>
	<li class="nav-item"><div class="nav-link"><%= link_to 'Blogs', questions_path, class: "nav-color" %></div></li>
	<li class="nav-item"><div class="nav-link"><%= link_to 'Profile', profile_view_user_path(current_user.id), class: "nav-color"%></div></li>
	<div class="pull-right">
	<li class="nav-item"><div class="nav-link"><%= "#{current_user.title}:" " #{current_user.full_name}" %>!</div></li>
	<li class="nav-item"><div class="nav-link"><%= link_to 'Logout', logout_path, class: "nav-color", method: :delete %></div></li>
	</div>
<% else %>
	<li class="nav-item"><div class="nav-link"><%= link_to 'Login', login_path, class: "nav-color"%></div></li> 
	<li class="nav-item"><div class="nav-link"><%= link_to 'Sign up now',new_user_path, class: "nav-color" %></div></li>
	<div class="pull-right">
		<li class="nav-item"><div class="nav-link"><a href="http://www.stjosephstechnology.ac.in/web/it/index.php" class="nav-color" target="_blank">DEPARTMENT OF INFORMATION TECHNOLOGY</a></div></li> 
	</div>
<% end %>
</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coding-Club-Brogrammers</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


  
</head>

<body>


<%= render 'layouts/headernav'%>
<%= render 'layouts/flash'%>

<%= yield %>

<%= render 'layouts/footer'%>
</body>

<script type="text/javascript">
  $(document).ready(function(){
    setTimeout(function(){
    $('.alert').fadeOut();
    }, 5000);
  })
</script>
</html>